provide_settings:
  llm:
    provider: "OpenAI"
    config:
      model: "o1-mini"
#      api_key: "sk-xxxx"  # Uncomment to override the `OPENAI_API_KEY` set in the environment variable
#      base_url: ""

  reasoning_llm:
    provider: "OpenAI"
    config:
      model: "o1-preview"  # Using a more powerful model for reasoning tasks
      stream: true  # 启用流式输出
      verbose: true  # 启用详细日志
#      api_key: "sk-xxxx"  # Uncomment to override the `OPENAI_API_KEY` set in the environment variable
#      base_url: ""

  writing_llm:
    provider: "OpenAI"
    config:
      model: "gpt-4o"  # Using a model optimized for writing tasks
#      api_key: "sk-xxxx"  # Uncomment to override the `OPENAI_API_KEY` set in the environment variable
#      base_url: ""

#    provider: "DeepSeek"
#    config:
#      model: "deepseek-reasoner"
##      api_key: "sk-xxxx"  # Uncomment to override the `DEEPSEEK_API_KEY` set in the environment variable
##      base_url: ""

#    provider: "SiliconFlow"
#    config:
#      model: "deepseek-ai/DeepSeek-R1"
##      api_key: "xxxx"  # Uncomment to override the `SILICONFLOW_API_KEY` set in the environment variable
##      base_url: ""

#    provider: "PPIO"
#    config:
#      model: "deepseek/deepseek-r1"
##      api_key: "sk_xxxxxx"  # Uncomment to override the `PPIO_API_KEY` set in the environment variable
##      base_url: ""

#    provider: "TogetherAI"
#    config:
#      model: "deepseek-ai/DeepSeek-R1"
##      api_key: "xxxx"  # Uncomment to override the `TOGETHER_API_KEY` set in the environment variable

#    provider: "AzureOpenAI"
#    config:
#      model: ""
#      api_version: ""
##      azure_endpoint: "xxxx"  # Uncomment to override the `AZURE_OPENAI_ENDPOINT` set in the environment variable
##      api_key: "xxxx"  # Uncomment to override the `AZURE_OPENAI_KEY` set in the environment variable

#    provider: "Ollama"
#    config:
#      model: "qwq"
##      base_url: ""

  embedding:
    on_demand_initialize: false
    provider: "OpenAIEmbedding"
    config:
      model: "text-embedding-ada-002"
#      api_key: ""  # Uncomment to override the `OPENAI_API_KEY` set in the environment variable
#      base_url: "" # Uncomment to override the `OPENAI_BASE_URL` set in the environment variable
#      dimension: 1536 # Uncomment to customize the embedding dimension 


#    provider: "MilvusEmbedding"
#    config:
#      model: "default"

#    provider: "VoyageEmbedding"
#    config:
#      model: "voyage-3"
##      api_key: ""  # Uncomment to override the `VOYAGE_API_KEY` set in the environment variable

#    provider: "BedrockEmbedding"
#    config:
#      model: "amazon.titan-embed-text-v2:0"
##      aws_access_key_id: ""  # Uncomment to override the `AWS_ACCESS_KEY_ID` set in the environment variable
##      aws_secret_access_key: ""  # Uncomment to override the `AWS_SECRET_ACCESS_KEY` set in the environment variable
    
#    provider: "SiliconflowEmbedding"
#    config:
#      model: "BAAI/bge-m3"
# .    api_key: ""   # Uncomment to override the `SILICONFLOW_API_KEY` set in the environment variable   

  file_loader:
    on_demand_initialize: false
    provider: "PDFLoader"
    config: {}

#    provider: "JsonFileLoader"
#    config:
#      text_key: ""

#    provider: "TextLoader"
#    config: {}

#    provider: "UnstructuredLoader"
#    config: {}

  web_crawler:
    on_demand_initialize: false
    provider: "FireCrawlCrawler"
    config: {}

    # provider: "Crawl4AICrawler"
    # config: # Uncomment to custom browser configuration for Crawl4AI
    #   browser_config:
    #     headless: false
    #     proxy: "http://127.0.0.1:7890"
    #     chrome_channel: "chrome"
    #     verbose: true
    #     viewport_width: 800
    #     viewport_height: 600
    
#    provider: "JinaCrawler"
#    config: {}

  vector_db:
    on_demand_initialize: false
    provider: "Milvus"
    config:
      default_collection: "deepsearcher"
      uri: "./milvus.db"
      token: "root:Milvus"
      db: "default"

  # vector_db:      
  #   provider: "OracleDB"
  #   config:
  #     default_collection: "deepsearcher"
  #     user: ""
  #     password: ""
  #     dsn: ""
  #     config_dir: ""
  #     wallet_location: ""
  #     wallet_password: ""

query_settings:
  max_iter: 3

load_settings:
  chunk_size: 1500
  chunk_overlap: 100

rbase_settings:
  verbose: false
  database:
    provider: "mysql"
    config:
      host: "localhost"
      port: 3306
      database: "rbase"
      username: "root"
      password: "123456"
  oss:
    host: "http://localhost/"
  dict_path:
    cn: "database/dicts/rbase_dict_cn.txt"
    en: "database/dicts/rbase_dict_en.txt"
  api:
    log_file: "logs/api.log"
    summary_cache_days: 5
    summary_article_reference_cnt: 50
    discuss_chunk_cnt: 20
    host: "0.0.0.0"
    port: 8000
